# Generated by Django 2.2 on 2020-06-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('ProfilePicture', models.ImageField(upload_to='')),
                ('emailAddress', models.CharField(max_length=255)),
                ('roomNumber', models.IntegerField()),
                ('subjectstaught', models.CharField(max_length=255)),
            ],
        ),
    ]
