# Generated by Django 2.2 on 2020-06-23 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
