# Generated by Django 2.2 on 2020-06-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subjectstaught',
            new_name='subjectsTaught',
        ),
    ]
