# Generated by Django 2.2 on 2020-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200624_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phoneNumber',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
