# Generated by Django 2.2 on 2020-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='roomNumber',
            field=models.CharField(max_length=10),
        ),
    ]
